# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 573fbbf4a0cc07d0661dd55a3365d83a02be84e19391b9b661127aa1827331e85692961be3d6a02b8c9b22d1bd95b9b8cf3b5e6b1341e11e3542c4e8947ce868

test:
  secret_key_base: c5cd1efdd18817bd25bf05350f7e4980e8716282007f1826a108adbfd9f9e2dbd4d8ed0940eb7a7704899ddc2a2a76bc27b8bb4c8237084ef6f4989572dd1c0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
